### PR TITLE
Added support for uniBS

### PR DESCRIPTION
**Pull request by ceres-c**
I had to create this unofficial theme for my bachelor thesis discussion since my university does not provide a LaTeX template.

I know you're encouraging mubeamer right now, but that seemed to be too MU-specific, so here we are :)

### CODE REVIEW

**Comment by Witiko** [comment]
@ceres-c Thank you for sharing your template! By including the template into fibeamer, it will become part of [CTAN](http://ctan.org/) and TeX installations worldwide. Additionally, I can enter your template into the Overleaf Gallery: would you like me to do that?

**Comment by ceres-c** [comment]
That'd be great, thanks! I don't have an Overleaf account
I hope I got everything right and didn't forget some important information. I'm new to beamer presentations and I rushed this in a couple of hours while being late for actually writing the presentation

**Comment by Witiko** [comment]
It's not a problem to update the template later.

**Comment by ceres-c** [comment]
Yeah, I meant I was hoping I did not miss anything out about the project and I added all the necessary files :)

**Comment by Witiko** [comment]
I will let you know if anything is missing. 😉  I hope your thesis defense went well.

**Comment by ceres-c** [comment]
Thanks!
I'll let you know in a couple of days, but how could it go wrong? People will be distracted from my talking by the beautiful LaTeX typesetting of the slides :D

**Comment by Witiko** [comment]
I merged the latest changes from the master branch (removal of unit tests, addition of a GitHub Actions workflow), added [a bunch of additional information](https://github.com/ceres-c/fibeamer/commit/4c64838#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52) to the Makefile, symlinked shared resources (the Jabberwocky) so that we don't cause grief to CTAN maintainers, and incremented the version number.

> I'll let you know in a couple of days, but how could it go wrong? People will be distracted from my talking by the beautiful LaTeX typesetting of the slides :D

That's the spirit! How did it go? :wink:

**Review by Witiko — APPROVED** [review]

**Comment by ceres-c** [comment]
Great, thanks!
It went nice, my supervisor helped me getting in the mood for an academic presentation and that really payed out. Thanks for this theme :)

**Comment by Witiko** [comment]
@ceres-c Congratulations. I have just published your theme to [the Overleaf gallery](https://www.overleaf.com/latex/templates/fibeamer-for-the-university-of-brescia-in-italy/hsmyprgscvjn).

**Comment by ceres-c** [comment]
This is way overdue, but thanks a lot for your work :)

**Pull request merged**
